### ISSUE TITLE
编辑器的网站打开白屏。

### ISSUE THREAD

**Issue by LeiD215** [phlinhng/b64-url-editor#4]
编辑器的网站https://www.phlinhng.com/b64-url-editor/ 打开白屏。
另外 请问我想自己做一个这个网站，请问应该怎么做？

**Comment by phlinhng** [comment]
你先掛梯子試試吧，我用香港 IP 打開是正常的。
網頁前端用的是 React，後端 API 用的是 Fastify。
你要搭建這個網頁的話，只要把源碼 clone 回本地再按照 React 的方式搭建就好。

**Comment by phlinhng** [comment]
改成 `114.114.114.114` 這個 DNS 試試

**Comment by LeiD215** [comment]
已经解决。
