### ISSUE TITLE
这次是爬梯子也打不开https://www.phlinhng.com/b64-url-editor了。

### ISSUE THREAD

**Issue by LeiD215** [phlinhng/b64-url-editor#6]
这次是爬梯子也打不开https://www.phlinhng.com/b64-url-editor了。换了好几个梯子也不行。
这次是直接提示无法连接到网站。

**Comment by phlinhng** [comment]
網站是託管在 github.io 上的，應該不會有問題（除非 github 掛了）。你直接 clone 到本地環境運行吧。

**Comment by phlinhng** [comment]
找到原因了， Cloudflare 神秘的防火墙自动把某些访问请求拦截了，还在寻找解决方法。

**Comment by LeiD215** [comment]
可以打开了。由于是菜鸟，本地环境搭建一直不会。

**Comment by LeiD215** [comment]
可以打开了。由于是菜鸟，本地环境搭建一直不会。

**Comment by LeiD215** [comment]
可以打开了。由于是菜鸟，本地环境搭建一直不会。

**Comment by phlinhng** [comment]
Github 的 TLS 證書最近有問題，網址將暫時換成 https://phlinhng.github.io/b64-url-editor/ 直到修復。

**Comment by phlinhng** [comment]
https://www.phlinhng.com/b64-url-editor 已修復。
