### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by vcarus** [phlinhng/b64-url-editor#8]
Try to deploy on my own server. There's an issue.

```
 FAIL  src/App.test.js
  ● Test suite failed to run

    Cannot find module './submit' from 'App.js'

    However, Jest was able to find:
    	'./App.css'
    	'./App.js'
    	'./App.test.js'

    You might want to include a file extension in your import, or update your 'moduleFileExtensions', which is currently ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'].

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      12 | import './App.css';
      13 | import { Logo } from './img';
    > 14 | import { apiBaseURL } from './submit';
         | ^
      15 | import 'github-fork-ribbon-css/gh-fork-ribbon.css';
      16 |
      17 | const { TextArea } = Input;

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/App.js:14:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        21.785s
Ran all test suites.
```

**Comment by phlinhng** [comment]
[`submit.js`](https://github.com/phlinhng/b64-url-editor/blob/master/src/submit.js) was missing due to my negligence. I had fixed it now. Please try again and feel free to report coming results.

**Comment by vcarus** [comment]
Thanks. It's working now.

BTW. Is there an open source repo for the API server (https://api.phlin.cc/b64)?

**Comment by phlinhng** [comment]
Working on it. I was afraid that make API open source will cause security issue due to leaking salt. I will open the API server until I figure out how to wipe sensitive information.

**Comment by vcarus** [comment]
Cool. Looking forward to it.
Maybe generate random salt for each install can just make it happen.

**Comment by phlinhng** [comment]
> Cool. Looking forward to it.
> Maybe generate random salt for each install can just make it happen.

@vcarus Sorry to inform that I will no longer maintain the subscription api since the server had run out of space and I have no spare time to re-deploy it. The source code of backend is now available at [@phlinhng/b64-url-editor-backend](https://github.com/phlinhng/b64-url-editor-backend).
